---
title: "Reproducible Research: Peer Assessment 1"
author: "SatyaBharat"
output: 
  html_document:
    keep_md: true
---


## Activity Monitor Data Assignment

```{r libraryload, echo=TRUE}

library(knitr, quiet=T)
library(plyr, quiet=T)  
library(ggplot2, quiet=T) 
opts_chunk$set(dev="png", fig.path="figure/")

```

## Loading and preprocessing the data

```{r Preprocess, echo=FALSE}

if (!file.exists("activity.csv")) stop("File does not exists")
monitor <- read.csv("activity.csv", header=TRUE, 
                     colClasses=c("numeric", "character", "numeric"),
                     stringsAsFactors=FALSE)
monitor$date.factor <- as.factor(monitor$date)
monitor$date <- as.Date(monitor$date, format="%Y-%m-%d")

```


## What is mean total number of steps taken per day?

```{r stepsperday, echo=FALSE}

monitor.daily <- ddply(monitor, .(date.factor), summarize,
                        total.steps=sum(steps, na.rm=TRUE))
hist(monitor.daily$total.steps, col="yellow", main=" Activity",
     xlab="no.of Steps Per Day")


pdaymean <- mean(monitor.daily$total.steps, na.rm=TRUE)
pdaymedian <- median(monitor.daily$total.steps, na.rm=TRUE)
cat(paste("The mean number of steps per day is", 
          format(pdaymean, digits=4), "and the median is", 
          format(pdaymedian, digits=2), "(ignoring missing values"))
```




## What is the average daily activity pattern?

```{r dailyactivitypattern, echo=FALSE}

monitor.pattern <- ddply(monitor, "interval", summarize,
                          mean=mean(steps, na.rm=TRUE))
g <- ggplot(monitor.pattern, aes(interval, mean))
g + geom_line(color="green") + 
  labs(title="Fitness monitor", 
       x="Interval through day (min)",
       y="Mean no.of steps")

```


## Imputing missing values

```{r ImputingMissing, echo=FALSE}

nmissing <- sum(!complete.cases(monitor))

cat(paste("Number of rows with missing data:", nmissing))

impute.value <- function(steps, interval) {
    if (is.na(steps)) {
        monitor.pattern[monitor.pattern$interval==interval,]$mean
    } else {
        steps
    }
}
imputed.monitor <- monitor

imputed.monitor$steps <- mapply(impute.value, monitor$steps, 
                                monitor$interval)

total.steps <- tapply(monitor$steps, monitor$date.factor,
                      sum, na.rm=TRUE)
total.steps.imputed <- tapply(imputed.monitor$steps,
                              imputed.monitor$date.factor, sum)
cat(paste("For the raw data the mean and median per day are:",
          format(mean(total.steps)), "and", median(total.steps)))
cat(paste("For the imputed the mean and median per day are:",
          format(mean(total.steps.imputed)), "and",
          format(median(total.steps.imputed))))

hist(total.steps.imputed, col="purple", main="Fitness Tracker Activity",
     xlab="Number of Steps Per Day (imputed)")


```


## Are there differences in activity patterns between weekdays and weekends?

```{r weekdayend, echo=FALSE}

daytype <- function(date) 
    if (weekdays(date) %in% c("Saturday", "Sunday")) "weekend" else "weekday"

imputed.monitor$day.type <- as.factor(sapply(imputed.monitor$date, daytype))


steps.day.daytype <- ddply(imputed.monitor, .(interval, day.type),
                           summarize, steps=mean(steps))

ggplot(steps.day.daytype, aes(interval, steps)) + 
    geom_line() + facet_grid(day.type ~ .) +
    labs(x="Time of Day (min)", y="Number of steps",
         title="Activity patterns on weekdays vs. weekends")

```


